name: Build Apricots
on:
  pull_request:
    branches:
      - runway
  push:
    branches:
      - runway
  schedule:
    - cron: '07 04 * * *'

jobs:
  build-native:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-10.15]
    steps:
      - uses: actions/checkout@v2
      - name: Install Linux dependencies
        if: startsWith(matrix.os, 'ubuntu-')
        run: |
          sudo apt-get update
          sudo apt-get install libsdl2-dev autotools-dev
      - name: Install Mac dependencies
        if: startsWith(matrix.os, 'macos-')
        run: brew install sdl2 autoconf automake
      - name: Build
        run: |
          ./bootstrap
          ./configure
          make
  build-source:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libsdl2-dev autotools-dev
      - name: Build
        run: |
          ./bootstrap
          ./configure
          make dist
      - name: Upload source distribution
        uses: actions/upload-artifact@v2
        with:
          name: source
          path: apricots-*.tar.gz
          if-no-files-found: error
